language: node_js

node_js:
  - node

branches:
  only:
    - master

install:
  - npm i
  - npm i -g now@17.0.3

script:
  - npm run build
  - npm run update
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script: npm run prod
  on:
    branch: master

notifications:
  email:
    recipients:
      - kiroschoi@outlook.com
    on_success: always
