language: node_js

node_js:
  - node

branches:
  only:
    - master

install:
  - npm i
  - npm i -D now@16.7.3

script:
  - npm run build
  - npm run update

deploy:
  provider: script
  script: npm run prod
  on:
    branch: master

notifications:
  email:
    recipients:
      - kiroschoi@outlook.com
    on_success: always
